//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSDataAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageVersion
    {
        public int Id { get; set; }
        public string Version { get; set; }
        public System.DateTime ReleaseDatetime { get; set; }
        public string SetupName { get; set; }
        public int PackageId { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
